### ISSUE TITLE
Websocket connection error

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/JuliaBox#14]
I am behind a firewall, and get this. I wonder if we can have a more seamless experience for folks behind firewalls - of course, each one has its own quirk.

![screen shot 2014-07-24 at 1 59 12 pm](https://cloud.githubusercontent.com/assets/744411/3685543/b48735ac-130c-11e4-9844-f31177603894.png)

**Comment by mturok** [comment]
Sorry to revive this - I'm actually having this problem in a fresh install, and not sure which switch to SSL you are referencing.....

**Comment by tanmaykm** [comment]
@mturok for a local install, you may be need to do the same as #307 if you see websocket errors.

**Comment by mturok** [comment]
Thank you. I actually tried that....was starting juliabox with
http://localhost, where localhost is my Ubuntu 14.04 running under
virtualbox on a Windows host.

Do I need to start juliabox with a fqdn name and use the fix below?

**Comment by tanmaykm** [comment]
Yes. That should most likely fix it.

If that doesn't. the other thing to check is whether your proxy/firewall configuration allow websockets in general.

**Comment by mturok** [comment]
Thank you again!   Will try in NYC am.   Great and simple design here for
something fairly sophisticated.

**Comment by ViralBShah** [comment]
Let's move the discussion to a new issue if we need to continue debugging.

**Comment by mturok** [comment]
Just an fyi that the issue was elated to the proxy server we have combined
with the need for a fqdn.   Not much more to debug but maybe something for
the README?

**Comment by tanmaykm** [comment]
Thanks. Yes, I think it should be mentioned in the setup steps.
