### ISSUE TITLE
plotting issues

### ISSUE THREAD

**Issue by mzalam** [JuliaLang/JuliaBox#156]
i tried to do some simple plotting using Gadfly. There are two issues I want to bring to your attentions:

1)
The first plot took almost 30 seconds to execute. The following is the code

f(x) = cos(x)^2;
plot([f], -25, 25) 

However, the subsequent plots are executed much faster. I logged out and logged in again to retry. Same issue. seems like that the first instances of the package is being executed way too slow.

2) 

After plotting, if I close and reopen the file, the plotted image disappears and instead of the image I get all the data points like the following:

x -100 -90 -80 -70 -60 -50 -40 -30 -20 -10 0 10 20 30 40 50 60 70 80 90 100 -90 -88 -86 -84 -82 -80 -78 -76 -74 -72 -70 -68 -66 -64 -62 -60 -58 -56 -54 -52 -50 -48 -46 -44 -42 -40 -38 -36 -34 -32 -30 -28 -26 -24 -22 -20 -18 -16 -14 -12 -10 -8 -6 -4 -2 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 -100 -50 0 50 100 -90 -85 -80 -75 -70 -65 -60 -55 -50 -45 -40 -35 -30 -25 -20 -15 -10 -5 0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 f(x) -1.5 -1.0 -0.5 0.0 0.5 1.0 1.5 2.0 2.5 -1.00 -0.95 -0.90 -0.85 -0.80 -0.75 -0.70 -0.65 -0.60 -0.55 -0.50 -0.45 -0.40 -0.35 -0.30 -0.25 -0.20 -0.15 -0.10 -0.05 0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80 1.85 1.90 1.95 2.00 -1 0 1 2 -1.0 -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0

 I tried the same with PyPlot. But neither is a problem with PyPlot. I cannot reproduce the Gadfly problem in my laptop by running Julia locally.

**Comment by tanmaykm** [comment]
Seems to be fixed in the recent version. Please reopen if not.
