### ISSUE TITLE
syncing with git in the screen problematic in one direction

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/JuliaBox#171]
From github to juliabox works fine
From juliabox to github works fine enough from the terminal not the sync screen

**Comment by tanmaykm** [comment]
Looks like your JuliaBox ssh key is not added to your github profile (https://help.github.com/enterprise/11.10.340/admin/articles/adding-an-ssh-key-for-shell-access/). You can get your ssh key from JuliaBox settings page.

Closing this for now. Please reopen if this did not solve it.

We shall be adding some help/instructions regarding this in the next JuliaBox refresh.
