### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/JuliaBox#175]
I think the tutorial will get auto-installed for new users, but should we provide a way for existing users to clone it from git, on our Sync page?

**Comment by tanmaykm** [comment]
Tutorials get auto-installed for all users now, unless the user already has a folder/file named `tutorial`.

**Comment by tanmaykm** [comment]
However, there's no way to get rid of it at the moment. That is, if the folder is deleted, it will be replaced the next time. I think that may be annoying for some. Will be putting a change to prevent it from coming back if deleted.

**Comment by ViralBShah** [comment]
Thanks. It's ok if it is there permanently for now.

**Comment by tanmaykm** [comment]
OK... let's leave it as it is for now.
