### ISSUE TITLE
Precompile PyPlot

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/JuliaBox#176]
I am opening a new issue for precompiling PyPlot. It does not take as much time as Gadfly to load, and hence is less of a burning issue. 

It is used as the default plotting method in the tutorial for now, and any optimization would be nice to have.

**Comment by ViralBShah** [comment]
PyPlot load time is about 10 seconds. Precompiled Gadfly is now about 3 seconds.

**Comment by tanmaykm** [comment]
Closing. Julia 0.4.0 and later precompile packages.
