### ISSUE TITLE
Tab completion for objects supporting dot operator

### ISSUE THREAD

**Issue by wbhart** [JuliaLang/JuliaBox#179]
Tab completion doesn't seem to work for objects that support the dot operator (e.g. types, Modules). It brings up a list of alternatives, but when one is selected, it appears to replace what was being typed, rather than append it after the dot. For example:

foo.TAB

might bring up "bar" as a possible completion. I click "bar" and I end up with

bar

instead of what I expected:

foo.bar

**Comment by tanmaykm** [comment]
This seems to be an issue with IJulia/IPython. Pressing `enter` instead of clicking on the list seems to work correctly in some cases.
