### ISSUE TITLE
Colons screw up indenting

### ISSUE THREAD

**Issue by wbhart** [JuliaLang/JuliaBox#180]
When entering Julia code containing colons, indenting is screwed up. E.g. consider the example:

```
type mytype
   a::Int
   b::Int
end
```

After each line containing a colon is typed, the next line is indented all the way to the end of the previous line.

**Comment by tanmaykm** [comment]
Changing the notebook type to Julia from the dropdown at the top right sets the correct indentation and highlighting. It is IPython by default. This needs to be done once while creating the notebook.

**Comment by tanmaykm** [comment]
Ideally the IPython profile should not appear at all, but it may need some tinkering to get that. We should try and have that in JuliaBox if possible.
