### ISSUE TITLE
MAT package

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/JuliaBox#183]
Could you pre-install the [MAT](https://github.com/simonster/MAT.jl) package?
As part of a tutorial I'd like to demonstrate reading .mat files.
Thanks!

**Comment by tanmaykm** [comment]
closed via #184

**Comment by ViralBShah** [comment]
Nice, this is generally useful.

BTW, I noted that the printing from loading mat files using MAT.jl is buggy - but it loads the matrices correctly.  Just FYI. I'll be filing an issue.

**Comment by timholy** [comment]
I could be wrong, but my memory is that all it does is return a Dict. So it just depends on how the Dict is printed by julia (i.e., this has nothing to do with MAT.jl per se).
