### ISSUE TITLE
Unicode in Output

### ISSUE THREAD

**Issue by lilinjn** [JuliaLang/JuliaBox#187]
Hi -- I am observing the following behavior (performed in a new notebook creating on juliabox):

In [1]: x = "♣"
Out[1]: "\u2663"

On my locally run notebook, I get
In [1]: x = "♣"
Out[1]: "♣"
(i'm running 0.3.4 on OSX)

running julia via the console on the juliabox, the console also escapes the unicode output just like the behavior in the notebook.

Is there a way to have the nicely formatted unicode strings?

**Comment by tanmaykm** [comment]
Not sure where this is coming from... On my Ubuntu laptop, I get `"\u2663"` with Julia 0.3.4 but "♣" with Julia 0.4.

**Comment by Keno** [comment]
At one point we were deciding printability based on the libc unicode tables. Not sure if we still do, but we might have switched to mojibake for that.

**Comment by lilinjn** [comment]
Since this likely has nothing to do with juliabox, I am closing, and will try investigating further based on Keno's comments; though perhaps the simplest thing to live with this until 0.4.
