### ISSUE TITLE
Console keyboard shortcuts

### ISSUE THREAD

**Issue by lilinjn** [JuliaLang/JuliaBox#188]
When running the juliabox console, shortcut keys copy and paste do not work (I'm on OSX/Chrome). 
Manually using the browser's edit menu is a work around for copy and paste.

**Comment by melvin0008** [comment]
Try control shift v

**Comment by lilinjn** [comment]
Thanks,  on a mac command-shift-v pastes text from the system clipboard into the console.  When copying, I end up selecting text with the mouse, and using command-c.  From my perspective, this issue is resolved.
