### ISSUE TITLE
Quandl

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/JuliaBox#189]
Adding Quandl will open up a very wide range of open source data. The package supports both TimeSeries' TimeArrays and DataFrames

**Comment by ViralBShah** [comment]
You can do `Pkg.add()` yourself. Do you think we should make it part of the default install? We want to make it so that the default set of packages is not too large (although we have added without too much thought for now), and that users can install their own packages and get updates.

**Comment by ViralBShah** [comment]
Otherwise, we update the image once a week. We'll do it as part of the next update, but there is the larger question about package management and default packages.

**Comment by milktrader** [comment]
Yeah, I think Quandl would be desirable as a default because of the wide range of data available, but I also see your point of getting a little bloated on default packages. 

When learning Julia, getting data to play with is nice though.

**Comment by ViralBShah** [comment]
The thing with preinstalled packages is the package management. What happens when you do Pkg.update() or you want a newer verison and it conflicts with an installed version.

For now, we'll install Quandl, but later on revisit the issue when streamlining the whole package story.

**Comment by milktrader** [comment]
Thanks!
