### ISSUE TITLE
Request to update the version of sympy

### ISSUE THREAD

**Issue by mw8** [JuliaLang/JuliaBox#196]
I was giving a live demo in class using Juliabox to solve some equations using SymPy.jl when I found that it gave an error when solving any equation with a constant at or below 10^(-8). Here is a minimal example of what I mean:

    using SymPy
    x = Sym("x");
    solve(1e-8*x)

    BoundsError()
    while loading In[1], in expression starting on line 3
    in solve at /home/juser/.julia/v0.3/SymPy/src/math.jl:287

The same code with 1e-8 replaced with 1e-7 works. This is a bug that is fixed in newer versions of SymPy, so I was wondering if we could update the SymPy installation used by JuliaBox from 0.7.4.1 to 0.7.6.

**Comment by ViralBShah** [comment]
You can do Pkg.update() to get the latest version.

**Comment by ViralBShah** [comment]
Unless you mean a newer version of SymPy and not SymPy.jl.

**Comment by mw8** [comment]
I mean SymPy, not SymPy.jl.

**Comment by tanmaykm** [comment]
SymPy is currently being installed using `apt-get` and the ubuntu repository only has `0.7.4.1`. We could switch to `pip` which installs the latest version. But I also notice that installing with `apt-get` pulls in lot of other packages, which look like fonts and texlive, which the `pip` installer does not. 

We could install the specific packages required if we have the list. But I suppose it would suffice to just do a `pip install --upgrade sympy` after the `apt-get`. 

Just trying to avoid getting into the details of install specific dependencies.

**Comment by ViralBShah** [comment]
Can the users do the pip install in their homedirectory and use that to override the system default?

**Comment by tanmaykm** [comment]
Yes, I suppose users could do `pip install --user --upgrade sympy` and the updated package would be picked up by `SymPy.jl`.

@mw8 Does this work for you?

**Comment by mw8** [comment]
It's not ideal, but it will work. Thanks.

**Comment by tanmaykm** [comment]
@mw8 I've also updated the docker script to install `sympy 0.7.6`. It will be available with the next update in a day or two. But you can also use `pip install --user` in the meantime. Thanks.

**Comment by mw8** [comment]
Much appreciated
