### ISSUE TITLE
Creation of folders without write permission prevents later log-in (problem restoring from backup)

### ISSUE THREAD

**Issue by jfhc** [JuliaLang/JuliaBox#201]
I encountered this issue by extracting a .tar file, which created folders without write permissions. After logging out of that session I was prevented from logging back into future sessions, getting an error message that the session could not be started.

There are more details on [Google Groups](https://groups.google.com/forum/#!topic/julia-box/Ja8CAqjqxnE).

This will apparently be fixed by [a commit](https://github.com/tanmaykm/JuliaBox/commit/87c35e1405143f3e47588d0496d771116015f9d4) from @tanmaykm.

Thanks for your help, Tanmay!

**Comment by tanmaykm** [comment]
fixed via https://github.com/tanmaykm/JuliaBox/commit/87c35e1405143f3e47588d0496d771116015f9d4 and https://github.com/tanmaykm/JuliaBox/commit/7ab84912b0555f02890502a80014ef3ef413b6dc#diff-5ec5c8cc56f48782e4d2e5712675ba51
