### ISSUE TITLE
Error when I try to view public SSH key

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/JuliaBox#203]
When I click View in the SSH Public Key line on the settings page,  I get a message ``Oops. Unexpected error while retrieving the ssh key. Please try again later.`` Is this supposed to work?

**Comment by davidanthoff** [comment]
Actually, my bad, one has to generate the SSH key manually on the command prompt for this to work. Maybe a better error message that says "go to console, generate ssh key" would make sense?

**Comment by tanmaykm** [comment]
JuliaBox will now generate ssh keys if they are not found.
The change will get applied on servers in a few hours.
Thanks for reporting.

**Comment by davidanthoff** [comment]
Great, thanks!
