### ISSUE TITLE
juliabox logo replaced now with jupyter

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/JuliaBox#218]
related to #216
I think we should bring back the juliabox logo
in the upper left of notebooks

I liked:
![image](https://cloud.githubusercontent.com/assets/862530/6505006/9d8ceb1c-c30b-11e4-8254-1fcf1c9646cd.png)

What I see now:
![image](https://cloud.githubusercontent.com/assets/862530/6505018/ad23fb42-c30b-11e4-8541-758e45956095.png)

**Comment by ViralBShah** [comment]
We should have JuliaBox - while also retain the jupyter logo - to show the partnership between the two projects. In fact the python logo on the top right should probably be replaced with the julia logo.

**Comment by tanmaykm** [comment]
Displaying the IJulia logo on JuliaBox notebooks.
Closed via #224
