### ISSUE TITLE
Install R kernel by default as well?

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/JuliaBox#219]
It would be helpful for doing comparisons (and demos) if this were available when explaining Julia to current R users.

**Comment by dmbates** [comment]
On the one hand, I would love to have an R kernel so that I could use the `RCall` package for Julia and get access to datasets and methods from R.

On the other hand, it would open the gates to having R users employing JuliaBox to run R notebooks.  There are a lot of R users and many of them are not sophisticated programmers.  Access to powerful computers is sometimes used as a blunt object with which to bludgeon the problem to death.

**Comment by jakebolewski** [comment]
Do you think this will really be a problem?  You could log the kernels being launched and just ban users who are abusing the system.  Python has more mature online hosted solutions so maybe this is not a problem in that case.

**Comment by ViralBShah** [comment]
Installing R would be ok - but we would burn through credits faster and end up having to support something that we are not equipped to. I guess at some point we will have to have a way to charge for JuliaBox with some basic stuff free - and then it would be fine if people want R or anything else.

I thought about doing it quietly, but once you introduce something and people start using it, it is difficult to remove it.

**Comment by jakebolewski** [comment]
That is fair. However, people do want to see how their existing workflow would work when moving or experimenting with Julia.  If the goal of JuliaBox is to try to entice these people to use Julia I think that is an important thing to keep in mind.  Every time I show this to people they ask about it so I thought it would be good to file an issue.

Using @dmbates RCall would only require R to be installed (with some common packages)? That might be a better solution.

**Comment by ViralBShah** [comment]
That is what I was leaning towards - to have R and key packages, and have things set up to work with RCall. Does someone know what Ubuntu packages to install for the common R packages?

**Comment by nalimilan** [comment]
I think that's `r-recommended`: http://cran.r-project.org/bin/linux/ubuntu/README

**Comment by dmbates** [comment]
`r-base` and `r-recommended` are the bare minimum.  For other packages there is a question of whether to use the Ubuntu package system or to allow installation of packages through the R package system.  If you want users to be able to run the R function `install.packages` then the Ubuntu `r-base-dev` (I believe that is the name) should be installed.  There are Ubuntu packages for specific R packages on CRAN, the R package archive.  So the widely used ggplot2 package will have its own Ubuntu package in a ppa.  I'll give more detail when I am sitting at an Ubuntu computer.

**Comment by ViralBShah** [comment]
If you have a list of common R packages available on Ubuntu, we will go with those.

**Comment by ViralBShah** [comment]
You can use apt-cache in the juliabox terminal and various dpkg commands as well - in case you don't want to wait to get to an ubuntu computer. :-)

**Comment by tanmaykm** [comment]
closed via https://github.com/tanmaykm/JuliaDockerImages/commit/e2827320ff125e199d7e0d7cf4de0d638274841c
