### ISSUE TITLE
Kernel dies during sparse linear solve

### ISSUE THREAD

**Issue by lruthotto** [JuliaLang/JuliaBox#221]
I ran into a strange problem today. After a few repetitions (5 should do) the following code makes the kernel crash for me on juliabox

```
B1 = sprandn(100,100,0.1)
B2 = speye(100)
x  = kron(B2,B1)\randn(100*100)
```
Can anyone reproduce this problem and knows how to fix it?

Also: I tried to follow the steps on https://github.com/JuliaLang/IJulia.jl to increase the verbosity of juliabox, but couldn't get it to work. Is this only working on local installations?

**Comment by jiahao** [comment]
Possibly JuliaLang/julia#10342?

**Comment by ViralBShah** [comment]
Quite possible. We need to update the PPAs.

**Comment by tanmaykm** [comment]
It seems to be different. Tests for issue https://github.com/JuliaLang/julia/issues/10342 seem to run fine.
But the error I get with this is:

````
julia> x  = kron(B2,B1)\randn(100*100)
julia: symbol lookup error: /usr/bin/../lib/x86_64-linux-gnu/julia/libcholmod.so: undefined symbol: dpotrf_
````

This is with the latest 0.3.6 binary install. Is it some deps version mismatch?

**Comment by ViralBShah** [comment]
Cc: @staticfloat @andreasnoack  This certainly seems to be an older version of SuiteSparse. Which one are we using?

**Comment by andreasnoack** [comment]
@tanmaykm How are `B1` and `B2` defined?

@ViralBShah We are using CHOLMOD 3.0.4 from SuiteSparse 4.4.3

**Comment by tanmaykm** [comment]
I tried the snippet from this issue description:
````
B1 = sprandn(100,100,0.1)
B2 = speye(100)
x  = kron(B2,B1)\randn(100*100)
````

**Comment by tkelman** [comment]
> We are using CHOLMOD 3.0.4 from SuiteSparse 4.4.3

Only on the julianightlies PPA. The juliareleases PPA looks like it's on 4.2.0. For generic binaries from master, `Versions.make` says 4.4.2, and release-0.3 is on 4.2.1.

**Comment by tkelman** [comment]
`dpotrf` should be coming from lapack. I think on the PPA we use openblas for blas but netlib for lapack.

**Comment by ViralBShah** [comment]
Should we install Julia on JuliaBox using the tarball, rather than the PPA - so that we get all the right libraries?

**Comment by tkelman** [comment]
I think it's easier to control everything that way, and we don't need to wait for Elliot to fix the PPA when problems happen. We might occasionally need Elliot to fix the buildbots if something breaks there, but we haven't had many issues with them.

Since JuliaBox is using docker and needs to rebuild the container image anyway to update versions, I don't think using the PPA has any specific advantages here.

**Comment by ViralBShah** [comment]
Yeah - this seems the way to go for 0.3.6. Also, we can start publishing these as the docker containers then.

**Comment by tanmaykm** [comment]
Reusing the PPA does make it a lot easier to build the JuliaBox images though.

There are already quite a bit of dependencies that JuliaBox needs to build for the packages. It currently uses the automated trustedbuild facility of dockerhub. And dockerhub does not act nicely with images that take too long to build.

**Comment by tkelman** [comment]
@tanmaykm see https://gist.github.com/anonymous/9db1ce5252adbe8c9803 for a rough sketch - should be faster to build (`curl | tar`) than using the PPA.

**Comment by andreasnoack** [comment]
I'm apparently not fully awake yet so sorry for the misinformation about the versions. I should have checked `Versions.make` instead of guessing and read the top of this issue.

I've just tried to run the example on Ubuntu 14.10 with Julia release from @staticfloat's PPA and it works so I don't know why you are getting the error. Is your system up to date?

**Comment by tanmaykm** [comment]
@andreasnoack JuliaBox is built on 14.04. Will that make a difference? But doesn't installing from PPA install all dependencies for Julia? Then the base Ubuntu version should not matter.

@tkelman Thanks. Will try that. I misunderstood the tarball to be a source tarball.

**Comment by tkelman** [comment]
I guess the question is how recently was the PPA updated, since I think the suitesparse stuff was tweaked recently.

**Comment by staticfloat** [comment]
Yes, I recently (about a week ago) fixed some sparse stuff. Make sure
you've updated and upgraded your packages recently.

**Comment by tanmaykm** [comment]
@staticfloat I see this issue in a docker image built 4 days back using this Dockerfile and without any cache: https://github.com/tanmaykm/JuliaDockerImages/blob/master/base/v0.3/Dockerfile

Can you spot anything there that could be causing this?
I'm also going to try with a fresh build.

**Comment by tanmaykm** [comment]
Happens with a fresh build and also with this minimal Dockerfile:
````
FROM ubuntu:14.04

RUN apt-get install -y apt-utils software-properties-common \
    && apt-add-repository -y ppa:staticfloat/juliareleases \
    && add-apt-repository -y ppa:staticfloat/julia-deps \
    && apt-get update \
    && apt-get install -y julia=0.3.6-depsfix9-trusty \
    && apt-get clean

ENTRYPOINT /bin/bash
````

Strangely, the Julia banner shows:
````
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.6 (2015-01-08 22:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  x86_64-linux-gnu

julia> 
````

Shouldn't the date be a more recent one?

**Comment by staticfloat** [comment]
@tanmaykm I've built a new version (`julia-0.3.6-depsfix10`) which doesn't have the problem above.  Try updating and see if it's any better for you.  It also removes a bunch of dependencies (the dependencies are bundled within Julia itself) so you might want to `apt-get autoremove` afterwards.

**Comment by staticfloat** [comment]
The date isn't getting updated properly because of a trick of the build process.  Don't worry about it.  :P

**Comment by tanmaykm** [comment]
Thanks @staticfloat !
