### ISSUE TITLE
Julia in JuliaBox console is a bit unreadable

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/JuliaBox#223]
Could the default color scheme for the terminal be tweaked so this is a bit more usable?

![screen shot 2015-03-20 at 9 14 25 am](https://cloud.githubusercontent.com/assets/1157798/6752092/9f4879b2-cee1-11e4-87d6-dbb5a2728497.png)

**Comment by ViralBShah** [comment]
If you have something in mind, can you submit a PR?

**Comment by jakebolewski** [comment]
Sure, where would this be defined?  In the terminal config or in some css file somewhere?

**Comment by ViralBShah** [comment]
Since we are using shellinabox, I guess that's where we have to look. @tanmaykm ?

**Comment by tanmaykm** [comment]
The `white-on-black.css` and `black-on-white.css` files here https://github.com/tanmaykm/shellinabox_fork/tree/master/shellinabox are the ones to be tweaked I think. There are a few other css files in the same folder that have the base color scheme.

**Comment by JeffBezanson** [comment]
+1 just ran into this. The dark gray on black is really bad.

**Comment by samuelpowell** [comment]
Fixed in tanmaykm/shellinabox_fork#3
