### ISSUE TITLE
Add TestImages.jl

### ISSUE THREAD

**Issue by shashi** [JuliaLang/JuliaBox#225]
@alanedelman wanted this.

**Comment by ViralBShah** [comment]
As I said in the other one - we really need a better way to deal with packages.

**Comment by alanedelman** [comment]
testimages is not urgent

**Comment by tanmaykm** [comment]
After #246, users are able to install and update packages and retain their own package directory across logins. Users can also have additional persistent disk space (on a case to case basis) when data or a package/library requires more that what's offered by default. JuliaBox will continue to bundle a smaller set of packages that are useful to most users though.
