### ISSUE TITLE
Add HypothesisTests.jl and Interact.jl

### ISSUE THREAD

**Issue by cfusting** [JuliaLang/JuliaBox#226]
Would love to see these added. Currently I add them on a per session basis.

Cheers,

_Chris

**Comment by ViralBShah** [comment]
I believe Interact.jl is already installed, but HypothesisTests needs to be.

We want to soon move to a setup with no default packages, but installed packages persisting.

**Comment by cfusting** [comment]
I think that would be perfect. I wonder how the problem of non-privileged users installing dependencies (like opencv, in my case) might be solved?

**Comment by ViralBShah** [comment]
Stick it in the home directory. There isn't enough space though - just 1GB. If you want opencv, we can stick it into the basic ubuntu image for now.

**Comment by cfusting** [comment]
For my particular use case I'd need Julia .4, openCV, and cxx.jl... Maybe more. Can hold on this for now.

**Comment by tanmaykm** [comment]
After #246, users are able to install and update packages and retain their own package directory across logins. Users can also have additional persistent disk space (on a case to case basis) when data or a package/library requires more that what's offered by default. JuliaBox will continue to bundle a smaller set of packages that are useful to most users though.
