### ISSUE TITLE
Installing QP solver on juliabox 

### ISSUE THREAD

**Issue by lruthotto** [JuliaLang/JuliaBox#230]
Hi all,
I am using juliabox for my optimization class and students like it. Thumbs up!

One (maybe small) problem I stumbled over was using JuMP to solve a quadratic program:

```
using JuMP
m = Model()
@defVar(m,  x )
@defVar(m,  y )
@setObjective(m, Min, (x-2)^2 + 2*(y-1)^2 )
@addConstraint(m, x - y >= 0)
@addConstraint(m, x + 4* y - 3 <= 0)
solve(m)
println("Final solution: [ $(getValue(x)), $(getValue(y)) ]")
```
It complains that there is no QP solver installed. So I tried installing Mosek, CPLEX and Gurobi usind Pkg.add. I wasn't able to build either of them. Does anyone know how to fix this? Thanks in advance!

Edit: I just saw that actually all of these packages require getting a license before Pkg.add() works, right? If that's the reason they are not installed this issue is probably solved.

**Comment by ViralBShah** [comment]
Those are all commercial solvers, so no easy solution there.

**Comment by lruthotto** [comment]
I see. Thanks for your info anyways...

**Comment by tkelman** [comment]
Ipopt solves QP's pretty well despite being designed for more general nonlinear problems. It just isn't in the default list of QP solvers in MathProgBase, but it could maybe be added there.

**Comment by aviks** [comment]
I can also confirm that Ipopt (surprisingly for me given the documentation in JuMP) solves QP's very well. It's saved my bacon recently when I had to do a demo at short notice on a machine that did not have any commercial solvers.
