### ISSUE TITLE
Feature request - add r-base-dev and r-recommended packages

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/JuliaBox#242]
To be able to use the `RCall` package for Julia there needs to be an R runtime environment accessible.  I believe that the `r-base-dev` and `r-recommended` Ubuntu packages should be sufficient to install R and the runtime environment and to ensure enough of a build environment to install R packages with binary dependencies.

**Comment by ViralBShah** [comment]
Do you also have a list of ubuntu R packages you'd like to see? We can do all of this in the next refresh in a couple of weeks or so, in the worst case.

**Comment by dmbates** [comment]
I may not be the best person to suggest such a list.  I don't actually use the Ubuntu packages to install R packages.  You end up with two package systems managing the same resources and things get too complicated.

**Comment by ViralBShah** [comment]
Do you usually just use R's package manager? That would actually be easier.

**Comment by tanmaykm** [comment]
closed via https://github.com/tanmaykm/JuliaDockerImages/commit/e2827320ff125e199d7e0d7cf4de0d638274841c

**Comment by simonbyrne** [comment]
Unfortunately the ubuntu supplied version is too old to use. Would it be possible to use the updated repository from CRAN?

I use the following on travis:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu precise/"
```
You may need to change `precise` to match whatever version of ubuntu you're using.

**Comment by tanmaykm** [comment]
@simonbyrne It will be great if you can send a PR updating https://github.com/tanmaykm/JuliaDockerImages/blob/master/pkgdists/juliabox/Dockerfile

**Comment by simonbyrne** [comment]
I don't really know how docker works: can I use the ubuntu repositories above?

**Comment by tanmaykm** [comment]
Yes, the JuliaBox image is based on Ubuntu trusty. So I guess what's required is:
`sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/"` ?

I can put that in before the next JuliaBox update.

**Comment by simonbyrne** [comment]
Thanks, much appreciated. You might need the `apt-key` line as well to avoid unknown signature errors.

**Comment by tanmaykm** [comment]
R is now installed from CRAN.

**Comment by simonbyrne** [comment]
Thanks!
