### ISSUE TITLE
Feature request: add option for nightly development kernels

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/JuliaBox#244]
Could it be possible to add this option so that instead of only having julia-release available, we could also use julia-nightly kernels? 

This would be nice because I'm already using Julia from JuliaBox almost all the time, at work I am always on the move, since julia-dev is not available I also use an account at koding.com with julia-nightly installed, but it doesn't support IJulia.

I know they are not really nightly builds but still is very useful especially to report bugs and such.

**Comment by ViralBShah** [comment]
Recently done in #243

**Comment by ViralBShah** [comment]
May not be deployed yet.

**Comment by Ismael-VC** [comment]
Cool ...it looks that way, I'll wait patiently!

Ismael Venegas Castelló
