### ISSUE TITLE
Juliabox session timestamps running ~1 min fast

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/JuliaBox#258]
I just noticed that on starting a new session on juliabox.org, under 'Profile and session info', the timestamps seem to be a minute faster than the actual time. See 'Session initialized at:'

Small issue, but I thought it could cause some problems?

**Comment by tanmaykm** [comment]
Those are based on server time, and it can possibly be different from your local machine time. I believe we do run NTP. And the time remaining display always displays it floored to the previous minute.

That shouldn't affect anything though.

**Comment by ianshmean** [comment]
Given I've observed my local machine time to be a lot more accurate to NIST time, I thought it was just worth noting. Perhaps NTP isn't working? But I agree that it's a very low risk issue, just thought I'd point it out if it's an easy fix.

Happy to close this if it's not worth the effort.

**Comment by tanmaykm** [comment]
Thanks for catching this! It turns out that we are not running ntpd.
Fixed image will roll out with the next update.

**Comment by ianshmean** [comment]
heh! No worries.
