### ISSUE TITLE
(Non-fatal) errors during juliabox image build

### ISSUE THREAD

**Issue by samuelpowell** [JuliaLang/JuliaBox#263]
During the juliabox image build I note a few failures.

The first few failures are due to sudo failing on apt-get (sudo timeout? container configuration problem?) during Pkg.build. This affects, e.g.,  ```hfd5-tools``` , ```libnlopt0```, ```libcairo2```, ```libmagickwand5```, ```tcl8.5``` which report errors such as:

```
INFO: Building HDF5
Installing dependency hdf5-tools via 'sudo apt-get install hdf5-tools':
sudo: no tty present and no askpass program specified
================================[ ERROR: HDF5 ]=================================

failed process: Process('sudo apt-get install hdf5-tools', ProcessExited(1)) [1]
while loading /opt/julia_packages/.julia/v0.3/HDF5/deps/build.jl, in expression starting on line 24

===============================================================================
```

Another failure occurs when configure cannot find gmp.h. 

```
configure: error: gmp.h header not found
================================[ ERROR: GLPK ]=================================

failed process: Process(setenv(`/opt/julia_packages/.julia/v0.3/GLPK/deps/src/glpk-4.52/configure --with-gmp --prefix=/opt/julia_packages/.julia/v0.3/GLPK/deps/usr`,Union(UTF8String,ASCIIString)["LDFLAGS= -L/opt/julia_packages/.julia/v0.3/GLPK/deps/usr/lib -L/opt/julia_0.3.11//lib -Wl,-rpath -Wl,/opt/julia_packages/.julia/v0.3/GLPK/deps/usr/lib","PATH=/opt/julia_packages/.julia/v0.3/GLPK/deps/usr/bin:/usr/local/texlive/2014/bin/x86_64-linux:/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin:/opt/julia/bin","SHLVL=1","PWD=/home/juser","JULIA_PKGDIR=/opt/julia_packages/.julia","HOME=/home/juser","PKG_CONFIG_PATH=/opt/julia_packages/.julia/v0.3/GLPK/deps/usr/lib/pkgconfig","HOSTNAME=80acce8971ef","_=/usr/bin/julia","CPPFLAGS= -I/opt/julia_packages/.julia/v0.3/GLPK/deps/usr/include -I/opt/julia_0.3.11//include"]), ProcessExited(1)) [1]
while loading /opt/julia_packages/.julia/v0.3/GLPK/deps/build.jl, in expression starting on line 61

================================================================================
```

**Comment by tanmaykm** [comment]
These errors are probably because the Dockerfile (`JuliaBox/docker/Dockerfile`) is based on `julialang/julia` instead of `julialang/juliaboxpkgdist`.

`julialang/juliaboxpkgdist` is a larger image and has all the libraries pre-installed for the packages JuliaBox uses. This is what is being used at juliabox.org. 

`julialang/julia` is much smaller and lacks those packages. This is useful for a development setup.

You could try either of the following:
- switch to `julialang/juliaboxpkgdist` and rebuild (`JuliaBox/scripts/install/img_create.sh build /jboxengine/data`)
- trim down the number of packages being installed from `JuliaBox/docker/setup_julia.sh`

**Comment by samuelpowell** [comment]
Got it.

The documentation you have recently produced has been extremely valuable in getting to grips with installing a JuliaBox development environment. I think I could add some helpful details for newcomers. 

Would you mind if I fork, open a PR for you to review, and if you think its useful perhaps merge?

**Comment by tanmaykm** [comment]
@samuelpowell Please do. It will be great to have more people install/contribute to JuliaBox.

**Comment by samuelpowell** [comment]
@tanmaykm, I will put something together. Thanks for your hep.
