### ISSUE TITLE
Use Julia provided build_sysimg.jl

### ISSUE THREAD

**Issue by samuelpowell** [JuliaLang/JuliaBox#270]
Is there any reason to add a copy of `build_sysimg.jl` when building the JuliaBox container? Could we not simply `include(joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl"))` in `mkjimg.jl`, thus ensuring the relevant version is always executed?

**Comment by tanmaykm** [comment]
Yes, we should use the one included in the Julia distribution.

I had added it to JuliaBox in the initial days of `build_sysimg.jl` when it was undergoing frequent changes and we were installing the `.deb` bundle (it was not included in that). But it's not required anymore.
