### ISSUE TITLE
Stalled on 'connecting to kernel'

### ISSUE THREAD

**Issue by samuelpowell** [JuliaLang/JuliaBox#271]
I am experiencing a problem with a fresh installation of JuliaBox in an Ubuntu 14.04 VM. Everything behaves as expected, except that notebooks stall with the orange 'Connecting to kernel' message in the top left corner, eventually timing out with the red 'Not connected' warning.

How might I debug this behaviour?

**Comment by tanmaykm** [comment]
Most likely cause for this is websocket connectivity issue. I would suggest the following:

1. enabling the browser debug console will show if the browser is able to connect websockets successfully
2. IJulia log files inside `/home/juser/.juliabox` folder of the JuliaBox session show any server side errors
3. least likely cause is an error on the webserver, but those are logged into `JuliaBox/webserver/logs/`

**Comment by samuelpowell** [comment]
@tanmaykm, thanks, it does appear to be websocket connectivity. I see the following error in the debug console upon (re-)launching a kernel:

```
[Log] Kernel: kernel_restarting (e7d74971-488b-4a14-bdad-5fd6c3f3b5fe) (kernel.js, line 98)
[Log] Kernel: kernel_created (e7d74971-488b-4a14-bdad-5fd6c3f3b5fe) (kernel.js, line 98)
[Log] Starting WebSockets: ws://jvbox/api/kernels/e7d74971-488b-4a14-bdad-5fd6c3f3b5fe (kernel.js, line 440)
[Error] WebSocket network error: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 2.) (Calling C and Python.ipynb, line 0)
[Log] Kernel: kernel_disconnected (e7d74971-488b-4a14-bdad-5fd6c3f3b5fe) (kernel.js, line 98)
[Log] Failed to reconnect, giving up. (kernel.js, line 545)
```
Note that:
 - There is no problem connecting from within the VM,
 - I have not had this problem on bare-metal,
 - I can see in the JuliaBox container that the Kernel is definitely launching,
 - I have tried disabling the firewall on the VM, to no avail.

This is a bit out of my comfort zone, so any advice appreciated.

**Comment by samuelpowell** [comment]
@tanmaykm okay, I think I understand what's wrong.

`Kernel.js` tries to open the websocket connection using the VM host name, which will not be resolvable on the connecting machine. Is there any way around this, or should we simply make it clear that the hostname of the server must be resolvable by hostname?

If the latter, I could start a FAQ (as development in a VM is quite useful).

**Comment by tanmaykm** [comment]
The hostname used for websocket connections is the one returned by `Compute.get_alias_hostname`. You can override that from the compute plugin.

The single instance plugin implementation just returns the same value as `Compute.get_instance_public_hostname` which is the same as python `socket.getfqdn()`. Does that not result in a resolvable hostname?

Also, browser security requires that to be the same as the hostname with which the page is accessed.

**Comment by samuelpowell** [comment]
This should be fine in deployment. 

I came about this problem because I was developing JuliaBox in a VM and accessing it by IP address, since the VM did not have an FQDN resolvable from the VM host.

**Comment by tanmaykm** [comment]
Closing this as not an issue. Please reopen if still an issue.
