### ISSUE TITLE
NA values using DataFrames

### ISSUE THREAD

**Issue by juanklopper** [JuliaLang/JuliaBox#277]
Juliabox is the only way that I can use Julia in a notebook.  Since upgrading to the newest Jupyter notebook, my Julia kernel just dies as soon as it starts.  Have tried so many remedies, to no avail.

Back to Juliabox.  Using the readtable() function (from DataFrames) reads CSV files just fine.  Unfortunately, using describe() on a column with a NA value returns: 
`isnan` has no method matching isnan(::NAtype)
while loading In[3], in expression starting on line 1
Since DataFrames was designed to deal with NA values, something's gone wrong.

PS, a similar problem was present using DataFrames in Juno.  That was easy to fix.  The Jewel package used in Juno referred to Dataarrays instead of DataArrays.

**Comment by tanmaykm** [comment]
If this is fixed in the latest DataFrames or its associated packages, probably updating packages will solve it. Can you try the following?

- `Pkg.add("DataFrames")`
- switch to non-precompiled packages (from the JuliaBox settings tab)
- restart the kernel if required

**Comment by tanmaykm** [comment]
@juanklopper packages were updated 3 days back, which should have addressed this. Closing this, please reopen if not.
