### ISSUE TITLE
juliabox.org is down

### ISSUE THREAD

**Issue by peterldowns** [JuliaLang/JuliaBox#302]
Returns a status header `503 Service Unavailable`

**Comment by ViralBShah** [comment]
This was an AWS outage. Things are back to normal now.

**Comment by ViralBShah** [comment]
https://groups.google.com/forum/#!topic/julia-box/_CVqq9yX8BI

**Comment by tanmaykm** [comment]
Amazon explains: https://aws.amazon.com/message/5467D2/

**Comment by jiahao** [comment]
There was a good suggestion to have a JuliaBox status page, even if it is as simple as fetching the AWS server status underneath.

**Comment by tanmaykm** [comment]
Thanks @jiahao, that's a great idea.

**Comment by chezou** [comment]
simple status page +1
