### ISSUE TITLE
Juliabox.org website dead kernel (0.3.11)

### ISSUE THREAD

**Issue by juanklopper** [JuliaLang/JuliaBox#303]
Have not being able to use 0.3.11 notebooks on the juliabox.org website since this morning (SA GMT+2).  Have tried all browsers (and Win10, Mac OSX, Fedora 22).  Dead kernel.
![deadkernel](https://cloud.githubusercontent.com/assets/8681335/10083637/99f48200-62ff-11e5-80ae-d724388ca6b9.PNG)

**Comment by tanmaykm** [comment]
Sorry about that... I presume you are able to use the 0.4 kernels. In that case, it may be due to outdated local packages. 

Could you try starting Julia in the console, and running a Pkg.update()? If you notice Pkg.update() updating some packages, notebooks will likely also start working fine.

**Comment by juanklopper** [comment]
Thanks so much!

**Comment by ViralBShah** [comment]
@tanmaykm Does this mean 0.3.11 fails for others too? I had to restart a notebook a couple of times yesterday myself, but it did work the second time - so I thought it was a transient issue.
