### ISSUE TITLE
Julia 0.3.11 no longer works

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/JuliaBox#305]
The kernel dies when starting. Julia 0.4 works just fine.

**Comment by tanmaykm** [comment]
Since #246, users can override JuliaBox provided packages.
Can you check if you have any such packages and whether they need to be upgraded?

**Comment by jiahao** [comment]
I see. Deleting .julia worked for me. Thanks

**Comment by ViralBShah** [comment]
How do we make this information more generally known to others? Should we post this as a PSA to julia-box? I am sure others are seeing this problem too.

**Comment by jiahao** [comment]
A more general broadcast would be useful. I'm not sure many JuliaBox users realize that they need to wipe their `.julia` directory from the Console window if it happens to them.

**Comment by ViralBShah** [comment]
@tanmaykm Could you make a PSA with these instructions? I think it will be greatly useful.

**Comment by ViralBShah** [comment]
Is there a better way to fix this for everyone? I get too many emails about this problem, and this has made people think that JuliaBox is unstable.

**Comment by nalimilan** [comment]
Maybe print an indication that removing `.julia` might help when a crash happens?

**Comment by tanmaykm** [comment]
What is the error message that Jupyter/IJulia throws in this case?

**Comment by ViralBShah** [comment]
Most people just report the kernel dying and disconnects. That is also what I have experienced. Usually gets fixed by deleting .julia.
