### ISSUE TITLE
Texlive issue

### ISSUE THREAD

**Issue by mykelk** [JuliaLang/JuliaBox#308]
My students have been using JuliaBox for [AA228](http://aa228.stanford.edu), but it appears that something happened with the packages included on texlive. We used to be able to do this:
```julia
using BayesNets
test = BayesNet([:A, :B])
test
```
but now it errors with "LaTeX Error: File `xunicode.sty' not found." I believe this can be fixed by ensuring that xunicode is included. You can add it using "tlmgr install xunicode", but my students aren't able to do this themselves:
```
juser@juliabox:~$ tlmgr install xunicode                                                                                                                                      
You don't have permission to change the installation in any way,                                                                                                              
specifically, the directory /usr/local/texlive/2014/tlpkg/ is not writable.                                                                                                   
Please run this program as administrator, or contact your local admin.                                                                                                        
tlmgr: An error has occurred. See above messages. Exiting.
```
Is this something that can be fixed?

**Comment by mykelk** [comment]
It was working just fine back when #113 was resolved.

**Comment by tanmaykm** [comment]
Thanks for pointing it out.

Is this something that can be installed with [tlmgr usermode](https://www.tug.org/texlive/doc/tlmgr.html#USER-MODE)?

If not, I suppose the [texlive.profile](https://github.com/tanmaykm/JuliaDockerImages/blob/master/pkgdists/juliaboxminimal/texlive.profile) used in image creation needs to be updated. I'm hoping to release a new image this weekend, and will include this change.

**Comment by mykelk** [comment]
Thanks! I got it working with this:
```
juser@juliabox:~$ tlmgr init-usertree                                             
tlmgr: action init-usertree returned a warning.                                   
juser@juliabox:~$ tlmgr --usermode install xunicode                               
tlmgr: package repository http://mirror.utexas.edu/ctan/systems/texlive/tlnet     
[1/1, ??:??/??:??] install: xunicode [26k]                                        
tlmgr: package log updated: /home/juser/texmf/web2c/tlmgr.log                     
running mktexlsr ...                                                              
done running mktexlsr.
```
It might be good if xunicode could be included in the image to reduce the steps required by students to get this going.

**Comment by ViralBShah** [comment]
We should be able to do that.

**Comment by tanmaykm** [comment]
fixed via https://github.com/tanmaykm/JuliaDockerImages/commit/9a84d5d7cffc4135e9c635844cec1df854c66e70
