### ISSUE TITLE
readline() hangs in 0.4.0-rc2 kernel

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/JuliaBox#309]
In the 0.3.11 kernel, the following works fine:

    sometext = readline()

This brings up a little box that says `STDIN>` which allows you to enter text for `readline()`. However, when the same code is submitted in the 0.4.0-rc2 kernel, no textbox appears; the kernel just hangs. When interrupted after submitting this code, the following messages appear:

    LoadError: InterruptException:
    while loading In[2], in expression starting on line 1

     in process_events at ./stream.jl:708
     in wait at ./task.jl:360
     in wait at ./task.jl:286
     in wait_readbyte at stream.jl:347
     in readuntil at stream.jl:924
     in readuntil at io.jl:162
     in readline at stream.jl:910
     in readline at stream.jl:912

This suggests to me that it's *trying* to read something, i.e. the `readline()` is working, but no means of entering text is given, so nothing happens.

It's not entirely clear to me whether this is an issue with JuliaBox, IJulia, or Jupyter, so if it's unrelated to JuliaBox I'd be happy to go bother someone else instead.

**Comment by tanmaykm** [comment]
Seems to be an issue with rc2. Works fine when updated to the final release.

**Comment by ararslan** [comment]
That's great! Any idea when the 0.4.0 release will go live on JuliaBox.org?

**Comment by tanmaykm** [comment]
They will go live on Saturday.

**Comment by tanmaykm** [comment]
fixed via #310
