### ISSUE TITLE
Juliabox cannot create instance.

### ISSUE THREAD

**Issue by cfusting** [JuliaLang/JuliaBox#321]
Just noticed this, not sure how long it has been down.

**Comment by ianshmean** [comment]
I just found the same with 0.4.0 but 0.5.0-dev instances do seem to start ok

**Comment by tanmaykm** [comment]
@cfusting JuliaBox seems to be up. Are you still unable to get through?

@ianshmean the error you see is probably because of package conflicts. Can you try updating/clearing local packages? There's a link in the settings page to do it now. See: #310

**Comment by ianshmean** [comment]
Ah, @tanmaykm that fixed it for me. Thanks. Nice to have that function gui'd!
