### ISSUE TITLE
missing files and notebooks and unable to log in

### ISSUE THREAD

**Issue by adrnp** [JuliaLang/JuliaBox#325]
Last night at around 10:30pm my session terminated.  Normally I am able to just log back in after a few minutes and start a new session, but was unable to do so last night and for the most part am still unable to do so.  I either get the spinning cog and then a message that my session has terminated / timed out or it just does nothing and goes back to the login page telling me an instance can't be created and to try again.

Of note is that is morning I was able to log in once (haven't been able to do so again) and pretty much all of my recent notebooks and files are gone.  The recent notebook remaining, when I tried to open it returned an error that I don't remember the exact wording of an can't log in to reproduce yet but was something along the lines of unable to open unsupported and there was a v4 in the first line of the text.

Unfortunately I did not have my files synced to my google drive, so I am wondering if there is any way of at least recovering the lost data?

**Comment by adrnp** [comment]
Here is the error when trying to open one of the couple remaining notebooks:

An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details.

**Comment by tanmaykm** [comment]
Extremely sorry to hear that. We currently keep only one version of the backed up files, so it's unlikely that we'll be able to recover older files.

I can try though, mostly to figure out the reason for this, if you share the JuliaBox user id that had this problem.

I'll close this in favor of #327 and #318, but we can continue the discussion here as needed.

**Comment by adrnp** [comment]
Not sure what you mean by JuliaBox user id, but I log in with my adrienp@stanford.edu<mailto:adrienp@stanford.edu> google account.  If you need something else, let me know where I can find it.

Thanks,
Adrien

**Comment by tanmaykm** [comment]
@adrnp Thanks, that's what I needed.

Your disk image seems to be exceeding the 500MB quota of juliabox.org. That would also be making logging in to your session slower with the risk of timing out when machines are loaded.

JuliaBox also needs some (a few MB of space) to keep per user configuration files and do some housekeeping stuff. Files may get truncated, if there's not enough space during the process. That's what likely caused the disk corruption in your case.

**Comment by adrnp** [comment]
Ah ok.  Is there a way for your end to remove the largest file (or couple files) to bring it back down well below the 500MB quota so at least juliabox is usable again for me?

**Comment by tanmaykm** [comment]
@adrnp Deleting specific files is difficult. But it is possible to re-initialize your disk. You will be able to login, but you'll have to re-populate all your files.

If you would like to download your old backup archive, we can set it up somewhere.

**Comment by adrnp** [comment]
It would be great if I could download my old backup archive, how would we go about doing that?

**Comment by tanmaykm** [comment]
@adrnp have reset your disk and sent a link to your old backup separately.

**Comment by adrnp** [comment]
Thank you very much for your help, I got all the files.

**Comment by gdowdy3** [comment]
@tanmaykm: I am experiencing a problem very similar to what adrnp experienced.  After a failed compilation of some Python code, I got an error message saying something like "the space is full".  Then, when I logged out of JuliaBox, I was unable to log back in.  

I just started using JuliaBox yesterday, so I don't have any important files associated with my account.  Could you clean out my files so that I can log in again?

**Comment by tanmaykm** [comment]
cc @nkottary

**Comment by nkottary** [comment]
Done.

**Comment by gdowdy3** [comment]
@tanmaykm @nkottary Thanks guys!

**Comment by gdowdy3** [comment]
Well, this is embarrassing... I've managed to lock myself out of JuliaBox again.  @nkottary, can you save me again?

As before, I got the "space full" error message.  This time, I know what line of code caused the error message, and I'll be careful to avoid replicating the situation in the future.

**Comment by nkottary** [comment]
I have cleared the backup.  We need a repair button to let the user download and delete the backup.

**Comment by gdowdy3** [comment]
Thanks again @nkottary, and I agree about the repair button!
