### ISSUE TITLE
/opt/julia_packages empty in juliabox container

### ISSUE THREAD

**Issue by mturok** [JuliaLang/JuliaBox#326]
I have built a single-user juliabox environment locally, and although I can run julia on the command line in the console, I can't open a julia notebook.

Turns out that /opt/julia_packages is empty - the tarball in ```/jboxengine/data/julia_packages.tar.gz``` was built on the host, but it isn't getting populated into the container.   Note that ```user_home.tar.gz``` is exploded properly as ```/home/juser```.  

Any suggestions?   I can "make" it work, but it didn't seem to work out of the box (then again, I have made several changes to the Dockerfile's to handle proxies with git, docker, aptitude, etc, etc).

Note that this seems to be a different problem than in #305 or #306 - and note that I can run python in the notebook. 

From ```~/.juliabox/ijuila_err.log``` on the juliabox console: 
```
ERROR: could not open file /opt/julia_packages/.julia/v0.4/IJulia/src/kernel.jl                                                                                                            
 in include at ./boot.jl:261                                                                                                                                                               
 in include_from_node1 at ./loading.jl:304                                                                                                                                                 
 in process_options at ./client.jl:308                                                                                                                                                     
 in _start at ./client.jl:411          
```

**Comment by tanmaykm** [comment]
Does `docker inspect` of the container show the packages path getting mounted on to the container? If not, probably something is amiss in the Dockerfile which is preventing that. Otherwise, something is preventing the packages tarball from being expanded in to the mounted folder. Probably related to file system permissions?

**Comment by mturok** [comment]
The packages path was mounted, but the tarball wasn't exploded (btw, having the shellinabox is a wonderful to debug a container).    I ended up forcing a change in ```engine/src/juliabox/plugins/vol_defpkg/defpkg.py``` in refresh_user_home_image(), to just call ```        JBoxDefaultPackagesVol._unpack_julia_packages()```.    Note that the root issue is that I had a packages directory that was empty, so that ```_has_unpacked_julia_packages()``` returned true.

I'm going to check in a completely clean build.

**Comment by mturok** [comment]
Resolved in a clean build.  Thanks!
