### ISSUE TITLE
hard-coded uid/gid of 1000 in mk_user_home.sh?

### ISSUE THREAD

**Issue by mturok** [JuliaLang/JuliaBox#329]
Just out of curiosity - I see that we have an assumption about a uid/gid of 1000 in mk_user_home.sh:  

https://github.com/JuliaLang/JuliaBox/blob/7cc66d23dfcc954f756a589a9f06ef73da8d9e73/container/interactive/mk_user_home.sh#L29

Is that following up on the assumption that juser is the first userid on the system?   Should this be something I replace if there are already other userids?

I note this comment here in the creation of the interactive/Dockerfile about creating specific userid's in that case.    

https://github.com/JuliaLang/JuliaBox/blob/7cc66d23dfcc954f756a589a9f06ef73da8d9e73/container/interactive/Dockerfile#L17

**Comment by mturok** [comment]
Maybe best to ask if we have the assumption of a "shared" uid/gid between the host and the docker containers, rather than approaches like this: http://stackoverflow.com/questions/23544282/what-is-the-best-way-to-manage-permissions-for-docker-shared-volumes

**Comment by mturok** [comment]
I just made it work by using the sudo to gid/uid 1000

**Comment by tanmaykm** [comment]
Yes. There are some dependencies to match the uid/gid to host uid/gid for a couple of reasons:

- We need access to the Docker IPC socket. I felt that having a uid dependency was better and more secure than changing permissions on the socket.
- We mount host devices directly for performance reasons and to enable AWS EBS volumes.

BTW, the latest version of docker (1.9 released a couple of weeks back) now has user namespaces, which can also be explored in this context.
