### ISSUE TITLE
Precompilation staleness check with docker still not working in 0.4.1?

### ISSUE THREAD

**Issue by mturok** [JuliaLang/JuliaBox#331]
I've started to use 0.4.1 to get this change, about issues with modification time checks for staleness with precompilation:  https://github.com/JuliaLang/julia/pull/13613.     

However, it still doesn't work for me - curious if anyone else seeing anything different.

Note that I'm forcing precompilation by adding a "using" statement right after the Pkg.add() in include_packages here:   

https://github.com/JuliaLang/JuliaBox/blob/master/container/interactive/setup_julia.sh

**Comment by tanmaykm** [comment]
Staleness check doesn't seem to be an issue anymore.
JuliaBox package bundles now contain precompiled packages after https://github.com/JuliaLang/JuliaBox/commit/0b70e6e70f626a987aa70adc59289d923be117e3
