### ISSUE TITLE
Increase visibility of session package reset function in preferences

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/JuliaBox#337]
An unaware colleague just lost a day to the failed kernel launch issue that can be fixed through the link in the preferences:
> Note: A conflict between system packages those installed by you may cause errors and failures while starting notebooks. In such cases, delete/update conflicting packages or *click here* to go back to using system installed packages only.

Even though they were directed to the preferences, they didn't see the option. Perhaps it needs a bolder title? Something like:
> **Kernel failing to initialise?**
> A conflict between system packages those installed by you may cause errors and failures while starting notebooks. In such cases, delete/update conflicting packages or *click here* to go back to using system installed packages only.

**Comment by tanmaykm** [comment]
Yes, good idea.
