### ISSUE TITLE
Juiliabox container build fails

### ISSUE THREAD

**Issue by barche** [JuliaLang/JuliaBox#342]
I get the following error when running the command `JuliaBox/scripts/install/img_create.sh cont build` with the `julialang/julia:v0.4.2` base image:

```
Step 14 : RUN /opt/julia-0.3/bin/julia  -e "try; Pkg.installed(\"JuliaWebAPI\"); catch; Pkg.clone(\"https://github.com/tanmaykm/JuliaWebAPI.jl\"); end"
 ---> Running in 50f9123320fc
/bin/sh: 1: /opt/julia-0.3/bin/julia: not found
The command '/bin/sh -c /opt/julia-0.3/bin/julia  -e "try; Pkg.installed(\"JuliaWebAPI\"); catch; Pkg.clone(\"https://github.com/tanmaykm/JuliaWebAPI.jl\"); end"' returned a non-zero code: 127
Error response from daemon: could not find image: no such id: juliabox/juliaboxapi:39
```

It seems to work when I remove the 0.3-related lines from the Docker file, but I'm not sure if that's the way it's intended to work? Did I miss a step in the install procedure?

**Comment by barche** [comment]
OK, that did the trick. I have my first zero-auth instance up and running now, thanks! I've added some small changed to the docs.

**Comment by ViralBShah** [comment]
BTW, are you trying to get this working locally or on AWS? If it is on AWS, we can share our AMI for JuliaBox.

**Comment by barche** [comment]
For now, just locally for development on an auth module. Later, I'd like to run our own juliabox server here on campus.
