### ISSUE TITLE
Kernels die in Julibox.org

### ISSUE THREAD

**Issue by ChristianKapfhammer** [JuliaLang/JuliaBox#345]
Hello everyone,

I have the current problem that some kernels in JuliaBox are dying all the time. At first I was using Julia 0.4.2. After some time, the kernels of all my files wouldn't connect anymore. Then I switched to 0.5.0-dev. It worked but after some time this kernel also stopped working. Now I had to switch to the current older version of Julia (0.3.12). But I fear that after some time it will stop working too.

I read some comments here of some people who seem to have the same problem as me.
Pkg.update() didn't seem to fix this.
I think I added some packages for plotting before it stopped working.

A detailed solution to this problem would be appreciated.

**Comment by ViralBShah** [comment]
0.3.12 is unlikely to stop working, because it has a different architecture. It would be useful to have a detailed set of steps to reproduce this.

Does resetting make 0.4.2 work again?

**Comment by ChristianKapfhammer** [comment]
At first, thanks for the quick answer.

Hmm, resetting to the system with installed packages only seemed to fix the problem.
0.4.2 and 0.5.0-dev are working again. It seems there where some package conflicts that corrupted my kernels.

The only packages I added where PyPlot and Gadfly via Pkg.add("PyPlot") and Pkg.add("Gadfly"). By doing this, my package system seemed to get corrupted. 

But now I have the issue that I am unable to add any new packages due to missing space. Here's the error message:

INFO: Initializing package repository /home/juser/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: cannot create directory at 'Timestamps': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

LoadError: failed process: Process(`git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
while loading In[2], in expression starting on line 1

 in run at ./process.jl:531
 in anonymous at pkg/dir.jl:52
 in cd at ./file.jl:22
 in init at pkg/dir.jl:50
 in cd at pkg/dir.jl:28
 in add at pkg.jl:23

**Comment by ChristianKapfhammer** [comment]
Nevermind, I see where the problem is. Time to delete some files....

Again, thanks for the help.
