### ISSUE TITLE
Write JuliaBox in Julia

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/JuliaBox#350]
I believe all the pieces are available for writing JuliaBox in Julia.

**Comment by ViralBShah** [comment]
We'll be doing this over time gradually. Not sure we need to keep an open issue for this. PRs are welcome, of course!

**Comment by EricForgy** [comment]
Understood. It is a shame that, arguably, the most public facing exposure to Julia is not itself written in Julia. This could be a good opportunity to demonstrate what a good Julia cloud-based application should look like. I'd definitely be interested in helping out with a rewrite. Sooner the better.

**Comment by ViralBShah** [comment]
I don't think consider this to be a shame. JuliaBox was written almost 18 months back, when the Julia ecosystem was considerably less mature. 

@tanmaykm can point out how to carry out this exercise. I do think it would be good to have such a roadmap, and I do agree its best to get started. Single node JuliaBox can run on almost any cloud platform, if you don't want all the features.

**Comment by EricForgy** [comment]
Yep yep. Totally agree. 18 months ago, it would have been difficult to do JuliaBox in Julia. Even today, it will not be easy, but would be great to have a roadmap and start the work :+1:
