### ISSUE TITLE
Julia code not working on JuliaBox

### ISSUE THREAD

**Issue by myGatz** [JuliaLang/JuliaBox#354]
Hi all,

I am having troubles having a code run on JuliaBox.
The code was first written in Matlab, then translated to Julia and it runs successfully on both Juno/LT and from console.
I wanted to upload it on JuliaBox and I did what follows: uploaded all the .jl files, made a Main.ipynb file with the line `include ("filename.jl")` and ran it. I get an error in the solver for the Ax=b system of equations as if A were singular, but I do not get that error on Juno, nor in the console, nor in the Matlab code.
I am working on Julia v.0.4.2 Kernel, the same version I have on my laptop.

The message I get is the following:

LoadError: Base.LinAlg.SingularException(0)
while loading In[2], in expression starting on line 118

 in umferror at sparse/umfpack.jl:22
 in solve at sparse/umfpack.jl:200
 in \ at linalg/factorization.jl:25
 in \ at linalg/generic.jl:326
 in mySolver at /home/juser/Code/mySolver.jl:39
 [inlined code] from In[2]:144
 in anonymous at no file:0

Latest update: right now the kernel Julia v.04.2 keeps dying without having the time to give the "run" command. Others kernel do not die but it looks the code is not compatible.

**Comment by tanmaykm** [comment]
The kernel dying issue could be one of https://github.com/JuliaLang/JuliaBox/issues/345 or https://github.com/JuliaLang/JuliaBox/issues/337

The error message seems unrelated.

**Comment by tanmaykm** [comment]
Issues referred to in #345 and #337 should not happen any more as JuliaBox has moved to Julia v0.4.3.
Closing this as fixed. Please reopen if this is unrelated and still occurs.
