### ISSUE TITLE
Preinstalled Ipopt is broken

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/JuliaBox#357]
Something happened between compilation and use that deleted `/usr/local/lib/libcoinmumps.so`, without which the package gives
```
Exception of type: OPTION_INVALID in file "IpAlgBuilder.cpp" at line 321:
 Exception message: Selected linear solver MA27 not available.
Tried to obtain MA27 from shared library "libhsl.so", but the following error occured:
libhsl.so: cannot open shared object file: No such file or directory
```
(if it fails to find mumps, it tried to look for ma27 which is not freely available).

Is `Pkg.test` being run on the preinstalled packages before updates are rolled out? I'd like to do a demo tomorrow, but the existing `/usr/local/lib/libipopt.so` is nonfunctional and there's no way I can see to force a source build. The library is present in the `julialang/juliaboxpkgdist:v0.3.12` docker image, I'm trying to hunt down where else it might have gotten deleted.

**Comment by tkelman** [comment]
cc @tanmaykm is JuliaBox not running one of the docker images available under julialang on docker hub any more? As a temporary resolution we could delete the libipopt.so from `/usr/local/lib` then BinDeps should fall back to the usual source build which should work.

**Comment by tanmaykm** [comment]
Yes, the image built recently does not have mumps installed. The reason seems to be that `mumps.enseeiht.fr` was inaccessible during the build. Strangely, it is still inaccessible from AWS machines. The following fails to connect:

````
juser@juliabox:~$ wget http://mumps.enseeiht.fr/
--2016-02-03 08:40:40--  http://mumps.enseeiht.fr/                                                                                                                                                                                        
Resolving mumps.enseeiht.fr (mumps.enseeiht.fr)... 147.127.176.144                                                                                                                                                                        
Connecting to mumps.enseeiht.fr (mumps.enseeiht.fr)|147.127.176.144|:80... ^C
````

Now re-building with image pulled from https://hub.docker.com/r/julialang/juliaboxpkgdist/tags/. I had switched to building everything on AWS some time back because dockerhub was unreliable then.

**Comment by tkelman** [comment]
I think it's working now, thanks so much! I'll see if I can send across a PR to hopefully make the docker image build more robust to download failures.
