### ISSUE TITLE
Julia Packages added through mk_user_home.sh not appearing in JuliaBox

### ISSUE THREAD

**Issue by jalving** [JuliaLang/JuliaBox#360]
Greetings!

I am trying to add a few extra Julia packages to my JuliaBox deployment (namely MPI and StochJuMP), but no matter what I do, any package I add never appears.  I'm using the mk_user_home.sh script to mount the archive to /opt/julia_packages in the container, but only the original julia packages appear.  I had originally tried installing them using the setup_julia entry point; it showed they successfully installed, but they still weren't there when I logged in.  Furthermore, the archive it writes back out to /jboxengine/data has the packages in it.  I tried completely rebuilding all of my containers and remounting, but still no luck.  

Is there something I'm fundamentally missing about mounting packages into docker?  Is there a cache somewhere I'm missing?  I even tried attaching to the docker container started in mk_user_home.sh, and that had the packages.  Where does this container fit in with the others?

If this doesn't work, is it considered good practice to add these directly to the docker image?

Thanks for any help,

Regards,

Jordan

**Comment by tanmaykm** [comment]
Hi Jordan, there is a package cache at `/jboxengine/data/packages/julia_packages` which probably needs to be cleared in this case. Issue `rm -rf /jboxengine/data/packages/julia_packages` to clear it. Restarting JuliaBox will then unpack the new bundle.

The suggested way to release modified/updated package bundles is to rename the bundle created by `mk_user_home.sh` to one with a version number/date suffix and have a plugin of type `JBP_PKGBUNDLE` manage the deployment. This is how it happens in the AWS deployment mode. It is not yet implemented in the standalone mode and hence clearing cache + restarting is required.

**Comment by jalving** [comment]
Thanks for the response.

The fix was certainly right under my nose.  I have not yet begun looking at the plugin options, but cache clearing is simple enough for my uses.

**Comment by tanmaykm** [comment]
Sure!
