### ISSUE TITLE
Change allocated memory and CPUs on custom juliabox install

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/JuliaBox#362]
The installation notes recommend tweaking docker to adjust memory and swap accounting, but this doesn't seem to affect the allocated memory and number of CPUs in the juliabox sessions.

Is there another setting to adjust these?

**Comment by tanmaykm** [comment]
I presume you followed instructions at https://docs.docker.com/engine/installation/linux/ubuntulinux/ to enable accounting at the system level.

After that, you also need to set the desired quota in the `/jboxengine/conf/jbox.user` configuration file. Parameter names (`cpu_limit`, `mem_limit`) can be looked up from [the template here]( https://github.com/tanmaykm/JuliaBox/blob/cb7298ece3b611bd022dd587092d81fab9893d11/engine/conf/tornado.conf.tpl).

**Comment by ianshmean** [comment]
Perfect, that did the trick. Thanks
