### ISSUE TITLE
LoadError: Failed to precompile JuMPeR

### ISSUE THREAD

**Issue by mandarup** [JuliaLang/JuliaBox#374]
`using JuMPeR`

INFO: Precompiling module JuMPeR...
WARNING: Method definition /(JuMP.GenericAffExpr{Float64, JuMPeR.Uncertain}, JuMP.GenericNormExpr{#P<:Any, #C<:Any, #V<:JuMPeR.Uncertain}) in module JuMPeR at /home/juser/.julia/v0.5/JuMPeR/src/robustops.jl:173 overwritten at /home/juser/.julia/v0.5/JuMPeR/src/robustops.jl:183.
WARNING: Method definition /(JuMP.GenericAffExpr{JuMP.GenericAffExpr{Float64, JuMPeR.Uncertain}, JuMP.Variable}, JuMP.GenericNormExpr{#P<:Any, #C<:Any, #V<:JuMPeR.Uncertain}) in module JuMPeR at /home/juser/.julia/v0.5/JuMPeR/src/robustops.jl:206 overwritten at /home/juser/.julia/v0.5/JuMPeR/src/robustops.jl:219.
ERROR: LoadError: LoadError: in @LinearConstraint (new_lhs <= unc_con.ub): expected comparison operator (<=, >=, or ==).
 in include(::ASCIIString) at ./boot.jl:240
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in include(::ASCIIString) at ./boot.jl:240
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 [inlined code] from ./boot.jl:243
 in anonymous at ./<no file>:4294967295
 in eval(::Module, ::Any) at ./boot.jl:243
 [inlined code] from ./sysimg.jl:11
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/juser/.julia/v0.5/JuMPeR/src/oracle.jl, in expression starting on line 72
while loading /home/juser/.julia/v0.5/JuMPeR/src/JuMPeR.jl, in expression starting on line 262

LoadError: Failed to precompile JuMPeR to /home/juser/.julia/lib/v0.5/JuMPeR.ji
while loading In[2], in expression starting on line 5

 in error(::ASCIIString) at ./error.jl:21
 in compilecache(::ASCIIString) at ./loading.jl:496
 in compilecache(::Symbol) at ./loading.jl:485
 in require(::Symbol) at ./loading.jl:355
 [inlined code] from ./essentials.jl:82
 in include_string(::ASCIIString, ::ASCIIString) at ./loading.jl:371

**Comment by ViralBShah** [comment]
Cc @IainNZ

**Comment by IainNZ** [comment]
This looks like 0.5, which JuMPeR doesn't support (and maybe not any release version of JuMP either?). I'm not planning on support 0.5 until a prerelease comes out.

**Comment by IainNZ** [comment]
@mandarup you should install Julia locally and use 0.4 - all the software will work just fine.

**Comment by IainNZ** [comment]
Ah I see Julia 0.4.5 is supported on JuliaBox, but I got some cryptic errors

```
INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/Calculus.ji for module Calculus.
WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.
WARNING: deserialization checks failed while attempting to load cache from /home/juser/.julia/lib/v0.4/Calculus.ji
INFO: Precompiling module Calculus...
INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/Calculus.ji for module Calculus.
WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.
```

Which I have no idea about, so again, definitely recommend local install.

**Comment by tanmaykm** [comment]
@IainNZ did you get this error in IJulia? If yes, it is probably because IJulia already loads Compat. Using the console to update packages would avoid that.

**Comment by IainNZ** [comment]
Yes IJulia.
I'm not sure how anyone would know to do that - maybe worth putting some sort of notice on the page about installing packages?

**Comment by tanmaykm** [comment]
Yes. I had added it (https://github.com/JuliaLang/JuliaBox/commit/c01276721abe3273e21c373467052b25f350024b) to the place where we list the installed packages on the JuliaBox settings page. But that's probably not the best place for that...

Please do mention if you think of something else more appropriate.
