### ISSUE TITLE
Silent deletion of files when setting up Git sync

### ISSUE THREAD

**Issue by matthew-lake** [JuliaLang/JuliaBox#375]
This is similar to  #369, but not a duplicate since that issue dealt with Google Drive sync.

When setting up git sync with a non-bare remote, any files in the specified local folder are deleted without warning. While this scenario might be uncommon, it can cause loss of notebooks.

While I recognize this maybe not be easy to fix, even a warning dialogue could alleviate the issue.

Steps to reproduce:
- Create notebooks (or other files) in a folder
- Set up git sync targeting that folder with a non-bare remote
- Sync

**Comment by tanmaykm** [comment]
Thanks for reporting. Yes, cloning a git repository deletes existing files to avoid conflicts during clone. Git conflicts are difficult to resolve with the simple user interface JuliaBox provides now.

This definitely needs a warning dialog.

**Comment by jmarcellopereira** [comment]
how to solve?
if I tried to synchronize the account " juliatutorialbr " the juliabox with the account " jmarcellopereira " ( this ) the github

**Comment by MaximilianJHuber** [comment]
I think just made the same mistake! I tried syncing my JuliaBox account "mjh635@nyu.edu" with GitHub and now JuliaBox only shows the "tutorial" folder, everything else is gone!
Can you help me retrieving my notebooks?
