### ISSUE TITLE
Plotting problem on the cloud-hosted Juliabox

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [JuliaLang/JuliaBox#383]
The cloud-hosted Juliabox (juliabox.org) is encountering problems whenever it ought to return a plot. For Winston, for instance:

<img width="1107" alt="screenshot 2016-05-08 11 05 05" src="https://cloud.githubusercontent.com/assets/2670100/15096947/fa274e2c-150c-11e6-92c1-3625f0b983c6.png">

Same for Plots. Could not test on Gadfly as it does not precompile. I am going to try to test if this is particular to the juliabox.org setup or JuliaBox in general, but I'm on an iPad at the moment.

**Comment by ViralBShah** [comment]
Winston is not really supported. Can you try PyPlot or Gadfly?

**Comment by tanmaykm** [comment]
PyPlot and Gadfly are working.

Precompiling packages from the console should work (may be failing from within a notebook because IJulia loads some packages already).
