### ISSUE TITLE
Big problem!

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaLang/JuliaBox#388]
I tried to sync with juliabox with github and files are gone !
How can I recover?

**Comment by tanmaykm** [comment]
dup of #375

**Comment by jmarcellopereira** [comment]
how to solve?
My notebooks are very important

**Comment by jmarcellopereira** [comment]
if I tried to synchronize the account " juliatutorialbr " the juliabox with the account " jmarcellopereira " ( this ) the github

**Comment by tanmaykm** [comment]
Unfortunately, it is difficult to retrieve the files back.
I'll give it a try though, and let you know offline.

**Comment by jmarcellopereira** [comment]
Ok , I await contact. I am very grateful for the help

**Comment by tanmaykm** [comment]
Closing. We were able to recover most files.
The core issue is open still.
