### ISSUE TITLE
PyCall returns a  MacroTools not defined error during precompilation

### ISSUE THREAD

**Issue by jalving** [JuliaLang/JuliaBox#391]
It seems that even from a fresh install of my JuliaBox, PyCall (and thus PyPlot) fails to precompile.

I am using julialang/julia:v0.4.5 as my base image.  My Dockerfile also installs a lot of extras, including scipy, numpy, and matplotlib.

The following error I get is:
****************************************************************************************************
[1] using PyCall
INFO: Precompiling module PyCall...
ERROR: LoadError: LoadError: UndefVarError: MacroTools not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /opt/julia_packages/.julia/v0.4/PyCall/src/io.jl, in expression starting on line 119
while loading /opt/julia_packages/.julia/v0.4/PyCall/src/PyCall.jl, in expression starting on line 178

LoadError: Failed to precompile PyCall to /home/juser/.julia/lib/v0.4/PyCall.ji
while loading In[1], in expression starting on line 1

 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:266
***************************************************************************************************
I can trace the error to io.jl, which is the end of function pyio_initialize(), but it isn't obvious what's failing to me.

I'm wondering if there's something off about the .cache folder I have setup.  If I go in as a user and use Pkg.add() to get PyPlot and its dependencies, and then clear the .cache folder in /home/juser/.julia, I can import the modules from the local .julia folder.  However, I would like to have it so the /opt/julia_packages directory works from the get go so users can just log in and run the julia notebooks.

Has this MacroTools error come up before?  Besides PyCall, all of the other modules will precompile.

**Comment by tkelman** [comment]
Not a JuliaBox-specific issue, this was reported a few times at PyCall I believe. I think it's been fixed by now?

**Comment by tanmaykm** [comment]
Yes. Works now.
