### ISSUE TITLE
Populate with some default notebooks

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/JuliaBox#40]
We should populate JuliaBox with some fun default notebooks. Simple ones demonstrating a couple of things to start, such as plotting, the julia manual chapters as notebooks, and then some nice ones such as "Colors of Chemistry".

We probably need some JuliaBox documentation too - a few lines on what JuliaBox is and how to use it.

Cc: @shashi

**Comment by tanmaykm** [comment]
Closed via #173
