### ISSUE TITLE
Error export PDF

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaLang/JuliaBox#404]
Hello everyone.
There was an error when I try to generate the pdf of notebooks with graphs/plots.
500 : Internal Server Error
The error was:
nbconvert failed: PDF creating failed

**Comment by tanmaykm** [comment]
Looks like this is because of https://github.com/jupyter/nbconvert/pull/140

I was able to create PDFs with absolute paths for images.
But using relative paths or HTTP URL throws this error.

Print preview works though, so the browser's "save as pdf" feature could be used as a workaround.

**Comment by jmarcellopereira** [comment]
ok, ;)

**Comment by slokhorst** [comment]
It would still be nice to have this working properly.. Can this issue be reopened?
