### ISSUE TITLE
Problem Cubature

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaLang/JuliaBox#405]
INFO: Installing Cubature v1.0.10
INFO: Building Cubature
INFO: Installing Cubature 1.0.2 library...
tar: cubature-1.0.2/clencurt.h: Cannot write: No space left on device
tar: cubature-1.0.2/cubature.h: Cannot write: No space left on device
tar: cubature-1.0.2/converged.h: Cannot write: No space left on device
tar: cubature-1.0.2/clencurt_gen.c: Cannot write: No space left on device
tar: cubature-1.0.2/ChangeLog: Cannot write: No space left on device
tar: cubature-1.0.2/README: Cannot write: No space left on device
tar: cubature-1.0.2/COPYING: Cannot write: No space left on device
tar: cubature-1.0.2/test.c: Cannot write: No space left on device
tar: cubature-1.0.2/pcubature.c: Cannot write: No space left on device
tar: cubature-1.0.2/hcubature.c: Cannot write: No space left on device
tar: Exiting with failure status due to previous errors
==============================[ ERROR: Cubature ]===============================

LoadError: failed process: Process(`tar xzf cubature-1.0.2.tar.gz --directory=.`, ProcessExited(2)) [2]
while loading /home/juser/.julia/v0.4/Cubature/deps/build.jl, in expression starting on line 17

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Cubature had build errors.

 - packages with build errors remain installed in /home/juser/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Cubature")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

How to solve?

**Comment by ViralBShah** [comment]
Disk space allocated is 500MB. We probably need to give a better message.

**Comment by jmarcellopereira** [comment]
strange ... cubature package is too large. I deleted several files and still continues.

**Comment by KristofferC** [comment]
It is probably the git repo history that is big? Have you had large files in the repo that you have later deleted? They still count for the repo size.

**Comment by jmarcellopereira** [comment]
I deleted other packages and files but still the error. I solved using julia locally.
