### ISSUE TITLE
The Julia 0.4.6 kernel in JuliaBox keeps dying 

### ISSUE THREAD

**Issue by ajt60gaibb** [JuliaLang/JuliaBox#424]
In JuliaBox the Julia 0.4.6 keeps dying.  The 0.3.12 and 0.5.0-dev kernels work as expected.   I am on a MacBook Pro 2015 with Google Chrome. 

Are others experiencing the same thing?

**Comment by ViralBShah** [comment]
Clean out your .julia in the settings?

**Comment by ajt60gaibb** [comment]
It worked. I did not know that. Thank you.

**Comment by gdowdy3** [comment]
Details on the procedure for "cleaning out your .julia in settings" can be found in #494.
